# Generated by Django 4.2.1 on 2023-06-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotPaidTurnoverSalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('insurance_sales', models.IntegerField(default=0, verbose_name='보험')),
                ('general_expense', models.IntegerField(default=0, verbose_name='일반경정비')),
                ('general_pando', models.IntegerField(default=0, verbose_name='일반판도')),
                ('general_rent', models.IntegerField(default=0, verbose_name='렌트일반')),
                ('rent_pando', models.IntegerField(default=0, verbose_name='렌트판도')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaidTurnoverSalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('insurance_sales', models.IntegerField(default=0, verbose_name='보험')),
                ('general_expense', models.IntegerField(default=0, verbose_name='일반경정비')),
                ('general_pando', models.IntegerField(default=0, verbose_name='일반판도')),
                ('general_rent', models.IntegerField(default=0, verbose_name='렌트일반')),
                ('rent_pando', models.IntegerField(default=0, verbose_name='렌트판도')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(verbose_name='마지막 날짜')),
                ('wage_turnover', models.IntegerField(default=0, verbose_name='공임매출')),
                ('component_turnover', models.IntegerField(default=0, verbose_name='부품매출')),
                ('charge_amount', models.IntegerField(default=0, verbose_name='청구금')),
                ('deposit_amount', models.IntegerField(default=0, verbose_name='입금액')),
                ('net_payment_amount', models.IntegerField(default=0, verbose_name='면책금')),
                ('not_paid_turnover_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='period_sales.notpaidturnoversalesinfo', verbose_name='미입금매출')),
                ('paid_turnover_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='period_sales.paidturnoversalesinfo', verbose_name='입금매출')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(verbose_name='마지막 날짜')),
                ('wage_turnover', models.IntegerField(default=0, verbose_name='공임매출')),
                ('component_turnover', models.IntegerField(default=0, verbose_name='부품매출')),
                ('charge_amount', models.IntegerField(default=0, verbose_name='청구금')),
                ('deposit_amount', models.IntegerField(default=0, verbose_name='입금액')),
                ('net_payment_amount', models.IntegerField(default=0, verbose_name='면책금')),
                ('not_paid_turnover_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='period_sales.notpaidturnoversalesinfo', verbose_name='미입금매출')),
                ('paid_turnover_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='period_sales.paidturnoversalesinfo', verbose_name='입금매출')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
