# Generated by Django 4.2.1 on 2023-06-30 20:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notpaidturnoversalesinfo',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 20, 31, 13, 598502, tzinfo=datetime.timezone.utc), verbose_name='종료일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notpaidturnoversalesinfo',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 20, 31, 17, 662639, tzinfo=datetime.timezone.utc), verbose_name='시작일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidturnoversalesinfo',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='종료일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidturnoversalesinfo',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='시작일'),
            preserve_default=False,
        ),
    ]
