# Generated by Django 4.2.1 on 2023-06-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0002_notpaidturnoversalesinfo_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notpaidturnoversalesinfo',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='notpaidturnoversalesinfo',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='paidturnoversalesinfo',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='paidturnoversalesinfo',
            name='start_date',
        ),
    ]
