# Generated by Django 4.2.1 on 2023-06-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0049_mockupcreated'),
        ('period_sales', '0003_remove_notpaidturnoversalesinfo_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysales',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='all_monthly_sales', to='demand.order', verbose_name='주문들'),
        ),
    ]
