# Generated by Django 4.2.1 on 2023-06-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0006_alter_monthlysales_not_paid_turnover_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysales',
            name='not_paid_turnover_info',
        ),
        migrations.RemoveField(
            model_name='monthlysales',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='monthlysales',
            name='paid_turnover_info',
        ),
        migrations.RemoveField(
            model_name='statisticsales',
            name='not_paid_turnover_info',
        ),
        migrations.RemoveField(
            model_name='statisticsales',
            name='paid_turnover_info',
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='not_paid_general_expense',
            field=models.IntegerField(default=0, verbose_name='[미입금]일반경정비'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='not_paid_general_pando',
            field=models.IntegerField(default=0, verbose_name='[미입금]일반판도'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='not_paid_general_rent',
            field=models.IntegerField(default=0, verbose_name='[미입금]렌트일반'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='not_paid_insurance_sales',
            field=models.IntegerField(default=0, verbose_name='[미입금]보험'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='not_paid_rent_pando',
            field=models.IntegerField(default=0, verbose_name='[미입금]렌트판도'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='paid_general_expense',
            field=models.IntegerField(default=0, verbose_name='[입금]일반경정비'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='paid_general_pando',
            field=models.IntegerField(default=0, verbose_name='[입금]일반판도'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='paid_general_rent',
            field=models.IntegerField(default=0, verbose_name='[입금]렌트일반'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='paid_insurance_sales',
            field=models.IntegerField(default=0, verbose_name='[입금]보험'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='paid_rent_pando',
            field=models.IntegerField(default=0, verbose_name='[입금]렌트판도'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='not_paid_general_expense',
            field=models.IntegerField(default=0, verbose_name='[미입금]일반경정비'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='not_paid_general_pando',
            field=models.IntegerField(default=0, verbose_name='[미입금]일반판도'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='not_paid_general_rent',
            field=models.IntegerField(default=0, verbose_name='[미입금]렌트일반'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='not_paid_insurance_sales',
            field=models.IntegerField(default=0, verbose_name='[미입금]보험'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='not_paid_rent_pando',
            field=models.IntegerField(default=0, verbose_name='[미입금]렌트판도'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='paid_general_expense',
            field=models.IntegerField(default=0, verbose_name='[입금]일반경정비'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='paid_general_pando',
            field=models.IntegerField(default=0, verbose_name='[입금]일반판도'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='paid_general_rent',
            field=models.IntegerField(default=0, verbose_name='[입금]렌트일반'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='paid_insurance_sales',
            field=models.IntegerField(default=0, verbose_name='[입금]보험'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='paid_rent_pando',
            field=models.IntegerField(default=0, verbose_name='[입금]렌트판도'),
        ),
        migrations.DeleteModel(
            name='NotPaidTurnoverSalesInfo',
        ),
        migrations.DeleteModel(
            name='PaidTurnoverSalesInfo',
        ),
    ]
