# Generated by Django 4.2.1 on 2023-07-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0007_remove_monthlysales_not_paid_turnover_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysales',
            name='attempted_amount',
            field=models.IntegerField(default=0, verbose_name='미수금'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='not_paid_recognized_sales',
            field=models.IntegerField(default=0, verbose_name='[미입금]인정매출'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_abroad_dongbu_insurances',
            field=models.IntegerField(default=0, verbose_name='동부보험(수입)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_abroad_etc_insurances',
            field=models.IntegerField(default=0, verbose_name='기타보험(수입)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_abroad_meritz_insurances',
            field=models.IntegerField(default=0, verbose_name='메리츠보험(수입)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_abroad_rent',
            field=models.IntegerField(default=0, verbose_name='렌트(수입)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_abroad_samsung_insurances',
            field=models.IntegerField(default=0, verbose_name='삼성보험(수입)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_domestic_dongbu_insurances',
            field=models.IntegerField(default=0, verbose_name='동부보험(국산)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_domestic_etc_insurances',
            field=models.IntegerField(default=0, verbose_name='기타보험(국산)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_domestic_meritz_insurances',
            field=models.IntegerField(default=0, verbose_name='메리츠보험(국산)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_domestic_rent',
            field=models.IntegerField(default=0, verbose_name='렌트(국산)'),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='number_of_domestic_samsung_insurances',
            field=models.IntegerField(default=0, verbose_name='삼성보험(국산)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='attempted_amount',
            field=models.IntegerField(default=0, verbose_name='미수금'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='not_paid_recognized_sales',
            field=models.IntegerField(default=0, verbose_name='[미입금]인정매출'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_abroad_dongbu_insurances',
            field=models.IntegerField(default=0, verbose_name='동부보험(수입)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_abroad_etc_insurances',
            field=models.IntegerField(default=0, verbose_name='기타보험(수입)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_abroad_meritz_insurances',
            field=models.IntegerField(default=0, verbose_name='메리츠보험(수입)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_abroad_rent',
            field=models.IntegerField(default=0, verbose_name='렌트(수입)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_abroad_samsung_insurances',
            field=models.IntegerField(default=0, verbose_name='삼성보험(수입)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_domestic_dongbu_insurances',
            field=models.IntegerField(default=0, verbose_name='동부보험(국산)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_domestic_etc_insurances',
            field=models.IntegerField(default=0, verbose_name='기타보험(국산)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_domestic_meritz_insurances',
            field=models.IntegerField(default=0, verbose_name='메리츠보험(국산)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_domestic_rent',
            field=models.IntegerField(default=0, verbose_name='렌트(국산)'),
        ),
        migrations.AddField(
            model_name='statisticsales',
            name='number_of_domestic_samsung_insurances',
            field=models.IntegerField(default=0, verbose_name='삼성보험(국산)'),
        ),
    ]
