# Generated by Django 4.2.1 on 2023-07-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0008_monthlysales_attempted_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysales',
            old_name='net_payment_amount',
            new_name='net_payment_sales',
        ),
        migrations.RenameField(
            model_name='statisticsales',
            old_name='net_payment_amount',
            new_name='net_payment_sales',
        ),
    ]
