# Generated by Django 4.2.1 on 2023-07-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0009_rename_net_payment_amount_monthlysales_net_payment_sales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlysales',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='statisticsales',
            options={'ordering': ['created']},
        ),
    ]
