# Generated by Django 4.2.1 on 2023-08-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0010_alter_monthlysales_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticSales',
        ),
    ]
