# Generated by Django 4.2.1 on 2023-08-11 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0012_alter_monthlysales_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysales',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
    ]
