# Generated by Django 4.2.11 on 2024-03-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0060_register_final_four_phone_number'),
        ('period_sales', '0013_alter_monthlysales_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysales',
            name='paid_insurance_sales_orderes',
            field=models.ManyToManyField(to='demand.order'),
        ),
    ]
