# Generated by Django 4.2.11 on 2024-03-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period_sales', '0015_rename_paid_insurance_sales_orderes_monthlysales_paid_insurance_sales_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysales',
            name='paid_insurance_sales_orders',
        ),
    ]
