# Generated by Django 4.2 on 2023-04-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('charge_date', models.DateField(verbose_name='청구일')),
                ('repair_amount', models.IntegerField(default=0, verbose_name='공임비')),
                ('component_amount', models.IntegerField(default=0, verbose_name='부품비')),
                ('indemnity_amount', models.IntegerField(default=0, verbose_name='면책금')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='담당 업체명')),
                ('active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deposit_amount', models.IntegerField(verbose_name='입금액')),
                ('deposit_date', models.DateField(verbose_name='입금일')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='보험 담당자명')),
                ('active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('indemnity_amount', models.IntegerField(blank=True, null=True, verbose_name='면책금')),
                ('discount_amount', models.IntegerField(blank=True, null=True, verbose_name='할인금')),
                ('payment_type', models.CharField(blank=True, choices=[('카드', '카드'), ('현금', '현금'), ('은행', '은행')], max_length=30, null=True, verbose_name='결제형태')),
                ('payment_info', models.CharField(blank=True, max_length=60, null=True, verbose_name='카드/은행')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='결제일')),
                ('refund_amount', models.IntegerField(blank=True, null=True, verbose_name='환불액')),
                ('refund_date', models.DateField(blank=True, null=True, verbose_name='환불일')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='지원 업체명')),
                ('active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('RO_number', models.CharField(max_length=10, verbose_name='RO번호')),
                ('car_number', models.CharField(max_length=20, verbose_name='차량번호')),
                ('day_came_in', models.DateField(verbose_name='입고일')),
                ('expected_day_came_out', models.DateField(blank=True, null=True, verbose_name='출고예정일')),
                ('real_day_came_out', models.DateField(blank=True, null=True, verbose_name='실제출고일')),
                ('car_model', models.CharField(max_length=90, verbose_name='차종')),
                ('abroad_type', models.CharField(choices=[('domestic', '국산'), ('imported', '수입')], max_length=10, verbose_name='국산/수입')),
                ('number_of_repair_works', models.IntegerField(blank=True, default=0, null=True, verbose_name='보수 작업판수')),
                ('number_of_exchange_works', models.IntegerField(blank=True, default=0, null=True, verbose_name='교환 작업판수')),
                ('client_name', models.CharField(max_length=30, verbose_name='고객명')),
                ('phone_number', models.CharField(max_length=15, verbose_name='전화번호')),
                ('rentcar_company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='렌트 업체명')),
                ('unrepaired', models.BooleanField(default=False, verbose_name='미수리출고')),
                ('wash_car', models.BooleanField(default=False, verbose_name='세차')),
                ('wasted', models.BooleanField(default=False, verbose_name='폐차')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('insurance_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='demand.insuranceagent', verbose_name='보험 담당자')),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers', to='demand.supporter', verbose_name='입고지원')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('order_type', models.CharField(choices=[('자차', '자차'), ('대물', '대물'), ('일반', '일반')], max_length=10, verbose_name='차/대/일')),
                ('charge_type', models.CharField(choices=[('보험', '보험'), ('일반경정', '일반경정'), ('일반판도', '일반판도'), ('렌트판도', '렌트판도'), ('렌트일반', '렌트일반'), ('인정매출', '인정매출')], max_length=20, verbose_name='구분')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='접수번호')),
                ('fault_ratio', models.IntegerField(verbose_name='과실분')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='demand.charge', verbose_name='청구')),
                ('charged_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='demand.chargedcompany', verbose_name='담당 업체명')),
                ('deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='demand.deposit', verbose_name='입금')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='demand.payment', verbose_name='결제')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='demand.register', verbose_name='등록')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
