# Generated by Django 4.2 on 2023-04-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='demand.charge', verbose_name='청구'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='demand.payment', verbose_name='결제'),
        ),
    ]
