# Generated by Django 4.2 on 2023-04-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_sales', to='demand.charge', verbose_name='청구')),
                ('deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_sales', to='demand.deposit', verbose_name='입금')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_sales', to='demand.payment', verbose_name='결제')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
