# Generated by Django 4.2 on 2023-04-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_extrasales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_info',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='은행사/카드사'),
        ),
        migrations.AlterField(
            model_name='register',
            name='client_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='고객명'),
        ),
    ]
