# Generated by Django 4.2 on 2023-04-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_alter_insurance_charge_alter_insurance_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deposit_amount', models.IntegerField(verbose_name='입금액')),
                ('deposit_date', models.DateField(verbose_name='입금일')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='insurance',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='demand.deposit', verbose_name='입금'),
        ),
    ]
