# Generated by Django 4.2 on 2023-04-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_alter_payment_payment_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='indemnity_amount',
        ),
    ]
