# Generated by Django 4.2 on 2023-04-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_deposit_alter_insurance_note_insurance_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='receipt_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='접수번호'),
        ),
    ]
