# Generated by Django 4.2 on 2023-04-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_alter_insurance_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unrepaired',
            field=models.BooleanField(default=False, verbose_name='미수리출고'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_day_came_out',
            field=models.DateField(blank=True, null=True, verbose_name='출고예정일'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_exchange_works',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='교환 작업판수'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_repair_works',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='보수 작업판수'),
        ),
        migrations.CreateModel(
            name='Wasted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wasted', to='demand.charge', verbose_name='청구')),
                ('deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wasted', to='demand.deposit', verbose_name='입금')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wasted', to='demand.payment', verbose_name='결제')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WashCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washcar', to='demand.charge', verbose_name='청구')),
                ('deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washcar', to='demand.deposit', verbose_name='입금')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washcar', to='demand.payment', verbose_name='결제')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='wash_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='demand.washcar', verbose_name='세차'),
        ),
        migrations.AddField(
            model_name='order',
            name='wasted',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='demand.wasted', verbose_name='폐차'),
        ),
    ]
