# Generated by Django 4.2 on 2023-04-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_remove_charge_indemnity_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호'),
        ),
    ]
