# Generated by Django 4.2 on 2023-04-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0005_order_unrepaired_alter_order_expected_day_came_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rentcar_company_note',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='메모'),
        ),
    ]
