# Generated by Django 4.2 on 2023-04-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0008_rename_repair_amount_charge_wage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasales',
            name='abroad_type',
            field=models.CharField(choices=[('domestic', '국산'), ('imported', '수입')], default='국산', max_length=10, verbose_name='국산/수입'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrasales',
            name='car_model',
            field=models.CharField(default='그랜저', max_length=90, verbose_name='차종'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrasales',
            name='car_number',
            field=models.CharField(default='TESTTEST', max_length=20, verbose_name='차량번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrasales',
            name='client_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='고객명'),
        ),
        migrations.AddField(
            model_name='extrasales',
            name='day_came_in',
            field=models.DateField(default='2019-01-01', verbose_name='입고일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrasales',
            name='expected_day_came_out',
            field=models.DateField(blank=True, null=True, verbose_name='출고예정일'),
        ),
        migrations.AddField(
            model_name='extrasales',
            name='number_of_exchange_works',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='교환 작업판수'),
        ),
        migrations.AddField(
            model_name='extrasales',
            name='number_of_repair_works',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='보수 작업판수'),
        ),
        migrations.AddField(
            model_name='extrasales',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='extrasales',
            name='real_day_came_out',
            field=models.DateField(blank=True, null=True, verbose_name='실제출고일'),
        ),
        migrations.AddField(
            model_name='extrasales',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_sales', to='demand.supporter', verbose_name='입고지원'),
        ),
    ]
