# Generated by Django 4.2 on 2023-04-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0009_extrasales_abroad_type_extrasales_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasales',
            name='insurance_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_extra_sales', to='demand.insuranceagent', verbose_name='보험 담당자'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_extra_sales', to='demand.supporter', verbose_name='입고지원'),
        ),
    ]
