# Generated by Django 4.2 on 2023-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0010_extrasales_insurance_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasales',
            name='abroad_type',
            field=models.CharField(blank=True, choices=[('domestic', '국산'), ('imported', '수입')], max_length=10, null=True, verbose_name='국산/수입'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='car_model',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='차종'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='차량번호'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='day_came_in',
            field=models.DateField(blank=True, null=True, verbose_name='입고일'),
        ),
    ]
