# Generated by Django 4.2 on 2023-04-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0011_alter_extrasales_abroad_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrasales',
            name='number_of_exchange_works',
        ),
        migrations.RemoveField(
            model_name='extrasales',
            name='number_of_repair_works',
        ),
    ]
