# Generated by Django 4.2 on 2023-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0012_remove_extrasales_number_of_exchange_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='접수번호'),
        ),
    ]
