# Generated by Django 4.2 on 2023-04-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0013_alter_order_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasales',
            name='unrepaired',
            field=models.BooleanField(default=False, verbose_name='미수리출고'),
        ),
        migrations.AddField(
            model_name='extrasales',
            name='wasted',
            field=models.BooleanField(default=False, verbose_name='폐차'),
        ),
    ]
