# Generated by Django 4.2 on 2023-04-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0014_extrasales_unrepaired_extrasales_wasted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='접수번호'),
        ),
    ]
