# Generated by Django 4.2 on 2023-04-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0015_alter_order_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='charge_date',
            field=models.DateField(blank=True, null=True, verbose_name='청구일'),
        ),
    ]
