# Generated by Django 4.2 on 2023-05-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0016_alter_charge_charge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charged_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='demand.chargedcompany', verbose_name='담당 업체명'),
        ),
    ]
