# Generated by Django 4.2 on 2023-05-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0018_alter_charge_charge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charge_type',
            field=models.CharField(choices=[('보험', '보험'), ('일반경정비', '일반경정비'), ('일반판도', '일반판도'), ('렌트판도', '렌트판도'), ('렌트일반', '렌트일반'), ('인정매출', '인정매출')], max_length=20, verbose_name='구분'),
        ),
    ]
