# Generated by Django 4.2 on 2023-05-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0023_alter_extrasales_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': '청구 정보', 'verbose_name_plural': '청구 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='chargedcompany',
            options={'verbose_name': '보험회사', 'verbose_name_plural': '보험회사(들)'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': '입금 정보', 'verbose_name_plural': '입금 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='extrasales',
            options={'verbose_name': '기타 매출', 'verbose_name_plural': '기타 매출(들)'},
        ),
        migrations.AlterModelOptions(
            name='insuranceagent',
            options={'verbose_name': '보험 담당자', 'verbose_name_plural': '보험 담당자(들)'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문 매출', 'verbose_name_plural': '주문 매출(들)'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '면책금 정보', 'verbose_name_plural': '면책금 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': '등록', 'verbose_name_plural': '등록(들)'},
        ),
        migrations.AlterModelOptions(
            name='supporter',
            options={'verbose_name': '입고 지원 업체', 'verbose_name_plural': '입고 지원 업체(들)'},
        ),
    ]
