# Generated by Django 4.2 on 2023-05-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0024_alter_charge_options_alter_chargedcompany_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['-created'], 'verbose_name': '청구 정보', 'verbose_name_plural': '청구 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='chargedcompany',
            options={'ordering': ['-created'], 'verbose_name': '보험회사', 'verbose_name_plural': '보험회사(들)'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created'], 'verbose_name': '입금 정보', 'verbose_name_plural': '입금 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='insuranceagent',
            options={'ordering': ['-created'], 'verbose_name': '보험 담당자', 'verbose_name_plural': '보험 담당자(들)'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created'], 'verbose_name': '면책금 정보', 'verbose_name_plural': '면책금 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['-created'], 'verbose_name': '등록', 'verbose_name_plural': '등록(들)'},
        ),
        migrations.AlterModelOptions(
            name='supporter',
            options={'ordering': ['-created'], 'verbose_name': '입고 지원 업체', 'verbose_name_plural': '입고 지원 업체(들)'},
        ),
    ]
