# Generated by Django 4.2.1 on 2023-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0026_alter_extrasales_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasales',
            name='status',
            field=models.CharField(choices=[('미청구', '미청구'), ('미입금', '미입금'), ('미출고', '미출고'), ('과입금', '과입금'), ('완료', '완료'), ('확인필요', '확인필요'), ('오류', '오류'), ('완료(수동)', '완료(수동)')], default='미청구', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('미청구', '미청구'), ('미입금', '미입금'), ('미출고', '미출고'), ('과입금', '과입금'), ('완료', '완료'), ('확인필요', '확인필요'), ('오류', '오류'), ('완료(수동)', '완료(수동)')], default='미청구', max_length=20, verbose_name='상태'),
        ),
    ]
