# Generated by Django 4.2.1 on 2023-05-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0027_alter_extrasales_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargedcompany',
            name='name',
            field=models.CharField(max_length=100, verbose_name='보험(렌트)'),
        ),
    ]
