# Generated by Django 4.2.1 on 2023-05-09 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0028_alter_chargedcompany_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charged_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='demand.chargedcompany', verbose_name='보험(렌트)'),
        ),
    ]
