# Generated by Django 4.2.1 on 2023-06-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0030_remove_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='incentive_paid',
            field=models.BooleanField(default=False, verbose_name='인센티브 지급'),
        ),
    ]
