# Generated by Django 4.2.1 on 2023-06-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0031_order_incentive_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrasales',
            name='unrepaired',
        ),
        migrations.RemoveField(
            model_name='extrasales',
            name='wasted',
        ),
        migrations.AddField(
            model_name='extrasales',
            name='sort',
            field=models.CharField(choices=[('세차', '세차'), ('폐차', '폐차'), ('미수리 출고', '미수리 출고'), ('기타', '기타')], default='기타', max_length=20, verbose_name='구분'),
            preserve_default=False,
        ),
    ]
