# Generated by Django 4.2.1 on 2023-06-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0036_alter_supporter_incentive_rate_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='incentive_rate_percent',
            field=models.IntegerField(default=15, verbose_name='지급율(%)'),
        ),
    ]
