# Generated by Django 4.2.1 on 2023-06-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0037_alter_supporter_incentive_rate_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('day_came_in', models.DateField(blank=True, null=True, verbose_name='입고일')),
                ('real_day_came_out', models.DateField(blank=True, null=True, verbose_name='출고일')),
                ('car_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='차량번호')),
                ('wage_amount', models.IntegerField(default=0, verbose_name='공임비')),
                ('request_department', models.CharField(max_length=100, verbose_name='요청부서')),
                ('component_amount', models.IntegerField(default=0, verbose_name='부품비')),
                ('note', models.TextField(blank=True, default='부가세 별도', null=True, verbose_name='비고')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
