# Generated by Django 4.2.1 on 2023-06-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0038_recognizedsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=30, verbose_name='요청부서명')),
                ('active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '요청부서',
                'verbose_name_plural': '요청부서(들)',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='recognizedsales',
            name='request_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand.requestdepartment'),
        ),
    ]
