# Generated by Django 4.2.1 on 2023-06-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0040_remove_register_wash_car_alter_extrasales_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recognizedsales',
            options={'ordering': ['-created'], 'verbose_name': '인정매출', 'verbose_name_plural': '인정 매출(들)'},
        ),
    ]
