# Generated by Django 4.2.1 on 2023-06-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0042_alter_charge_charge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasales',
            name='abroad_type',
            field=models.CharField(blank=True, choices=[('국산', '국산'), ('수입', '수입')], max_length=10, null=True, verbose_name='국산/수입'),
        ),
        migrations.AlterField(
            model_name='order',
            name='charge_type',
            field=models.CharField(choices=[('보험', '보험'), ('일반경정비', '일반경정비'), ('일반판도', '일반판도'), ('렌트판도', '렌트판도'), ('렌트일반', '렌트일반'), ('기타', '기타')], max_length=20, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='register',
            name='abroad_type',
            field=models.CharField(choices=[('국산', '국산'), ('수입', '수입')], max_length=10, verbose_name='국산/수입'),
        ),
    ]
