# Generated by Django 4.2.1 on 2023-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0043_alter_extrasales_abroad_type_alter_order_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='mockup',
            field=models.BooleanField(default=False, verbose_name='모형'),
        ),
    ]
