# Generated by Django 4.2.1 on 2023-06-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0044_deposit_mockup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='mockup',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='입금액'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='입금일'),
        ),
    ]
