# Generated by Django 4.2.1 on 2023-06-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0045_remove_deposit_mockup_alter_deposit_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': '청구 정보', 'verbose_name_plural': '청구 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': '입금 정보', 'verbose_name_plural': '입금 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '면책금 정보', 'verbose_name_plural': '면책금 정보(들)'},
        ),
    ]
