# Generated by Django 4.2.1 on 2023-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0046_alter_charge_options_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='component_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='부품비'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='wage_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='공임비'),
        ),
    ]
