# Generated by Django 4.2.1 on 2023-06-28 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0047_alter_charge_component_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasales',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_sales', to='demand.charge', verbose_name='청구'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_sales', to='demand.deposit', verbose_name='입금'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_sales', to='demand.payment', verbose_name='결제'),
        ),
        migrations.AlterField(
            model_name='order',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='demand.charge', verbose_name='청구'),
        ),
        migrations.AlterField(
            model_name='order',
            name='charged_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='demand.chargedcompany', verbose_name='보험(렌트)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='demand.deposit', verbose_name='입금'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='demand.payment', verbose_name='결제'),
        ),
        migrations.AlterField(
            model_name='order',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='demand.register', verbose_name='등록'),
        ),
    ]
