# Generated by Django 4.2.1 on 2023-06-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0048_alter_extrasales_charge_alter_extrasales_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문일')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.register', verbose_name='등록')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
