# Generated by Django 4.2.1 on 2023-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0050_order_incentive_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='incentive_paid',
            field=models.BooleanField(default=False, verbose_name='인센티브 지급여부'),
        ),
    ]
