# Generated by Django 4.2.1 on 2023-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0051_alter_order_incentive_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposit_note',
            field=models.TextField(blank=True, null=True, verbose_name='입금 정보'),
        ),
    ]
