# Generated by Django 4.2.1 on 2023-07-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0052_deposit_deposit_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supporter',
            options={'ordering': ['name'], 'verbose_name': '입고 지원 업체', 'verbose_name_plural': '입고 지원 업체(들)'},
        ),
    ]
