# Generated by Django 4.2.1 on 2023-07-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0053_alter_supporter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargedcompany',
            options={'ordering': ['name'], 'verbose_name': '보험회사', 'verbose_name_plural': '보험회사(들)'},
        ),
        migrations.AlterModelOptions(
            name='insuranceagent',
            options={'ordering': ['name'], 'verbose_name': '보험 담당자', 'verbose_name_plural': '보험 담당자(들)'},
        ),
    ]
