# Generated by Django 4.2.1 on 2023-07-09 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0055_alter_extrasales_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedsales',
            name='request_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand.requestdepartment', verbose_name='요청부서'),
        ),
    ]
