# Generated by Django 4.2.1 on 2023-07-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0056_alter_recognizedsales_request_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargedcompany',
            options={'ordering': ['name'], 'verbose_name': '보험사', 'verbose_name_plural': '보험사(들)'},
        ),
        migrations.AlterField(
            model_name='order',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='demand.register', verbose_name='등록'),
        ),
    ]
