# Generated by Django 4.2.1 on 2023-08-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0057_alter_chargedcompany_options_alter_order_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='chargedcompany',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='chargedcompany',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='insuranceagent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='insuranceagent',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='recognizedsales',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='recognizedsales',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='register',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='register',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='requestdepartment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='requestdepartment',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정시각'),
        ),
    ]
