# Generated by Django 4.2.1 on 2023-08-11 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0058_alter_charge_created_alter_charge_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='chargedcompany',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='extrasales',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='insuranceagent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='recognizedsales',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='register',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='requestdepartment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='생성시각'),
        ),
    ]
