# Generated by Django 4.2.1 on 2023-09-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0059_alter_charge_created_alter_chargedcompany_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='final_four_phone_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='전화번호 뒷자리'),
        ),
    ]
